export const LORE_MEMORY_SELECT = [
  "id",
  "chunk_text",
  "tags",
  "memory_kind",
  "temporal_status",
  "importance_score",
  "confidence_score",
  "source_thread_id",
  "source_message_id",
  "source_message_number",
  "is_pinned",
  "is_archived",
  "extraction_version",
  "last_confirmed_at",
  "valid_from",
  "valid_until",
  "event_time",
  "created_at",
].join(", ");
