const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { installAliasResolver, installTsLoader } = require("./testBootstrap.cjs");
installTsLoader();
installAliasResolver();
const { PROJECT_MEMORY_CHAT_MAX_CHARS } = require("../lib/project-memory/chat-inclusion-limits.ts");
const root = path.join(__dirname, "..");
const file = "migration_v204_project_memory_chat_inclusion.sql";
const pending = path.join(root, "docs", file);
const migration = fs.readFileSync(fs.existsSync(pending) ? pending : path.join(root, "docs", "applied", file), "utf8");
const schema = fs.readFileSync(path.join(root, "docs/schema.sql"), "utf8");
const normalize = sql => sql.replace(/--[^\r\n]*/g, " ").replace(/\s+/g, " ").trim();
const pattern = /create or replace function public\.set_project_memory_topic_chat_inclusion\([\s\S]*?grant execute on function public\.set_project_memory_topic_chat_inclusion\([\s\S]*?to authenticated;/g;
const definitions = sql => normalize(sql).match(pattern) ?? [];
assert.equal(definitions(schema).length, 1);
assert.equal(definitions(migration).length, 1);
const [rpc] = definitions(migration);
assert.equal(definitions(schema)[0], rpc);
assert.match(rpc, /p_user_id uuid, p_project_id uuid, p_topic_id uuid, p_include boolean \) returns table\(is_included boolean, included_chars integer\) language plpgsql security definer set search_path = ''/);
const body = rpc.split("as $$")[1].split("$$;")[0];
const steps = ["if p_user_id is null", "if p_include is null", "select t.project_id into v_project_id", "v_project_id is distinct from p_project_id", "perform 1 from public.projects p", "select t.include_in_chat, t.content_md into v_topic", "select coalesce(sum(char_length(t.content_md)), 0)::integer into v_others", "if v_topic.include_in_chat = p_include", "if p_include then", "if btrim(v_topic.content_md) = ''", "if v_others + char_length(v_topic.content_md) > c_max", "update public.project_memory_topics as t", "return query select p_include"];
const positions = steps.map(step => { const pos = body.indexOf(step); assert.ok(pos >= 0, step); return pos; });
for (let i = 1; i < positions.length; i++) assert.ok(positions[i] > positions[i - 1], `${steps[i]} must follow ${steps[i - 1]}`);
assert.ok(positions[4] < positions[5], "Project lock precedes topic lock");
assert.ok(positions[7] < positions[9] && positions[7] < positions[10], "same-value return precedes empty/limit checks");
assert.match(body.slice(positions[2], positions[4]), /where t.id = p_topic_id and t.user_id = p_user_id; if not found or v_project_id is distinct from p_project_id then/);
assert.match(body.slice(positions[4], positions[5]), /where p.id = v_project_id and p.user_id = p_user_id for update; if not found then/);
assert.match(body.slice(positions[5], positions[6]), /where t.id = p_topic_id and t.user_id = p_user_id and t.project_id = v_project_id for update; if not found then/);
assert.match(body.slice(positions[6], positions[7]), /where t.project_id = v_project_id and t.user_id = p_user_id and t.include_in_chat and t.id <> p_topic_id;/);
assert.match(body, /if v_topic.include_in_chat = p_include then return query select v_topic.include_in_chat, v_others \+ \(case when v_topic.include_in_chat then char_length\(v_topic.content_md\) else 0 end\); return; end if;/);
assert.match(body, /end if; end if; update public/);
assert.deepEqual(body.match(/update public[\s\S]*?;/g), ["update public.project_memory_topics as t set include_in_chat = p_include where t.id = p_topic_id and t.user_id = p_user_id;"]);
assert.doesNotMatch(body, /\brevision\b|project_memory_revisions|\binsert\b|\bdelete\b/);
assert.match(body, /return query select p_include, v_others \+ \(case when p_include then char_length\(v_topic.content_md\) else 0 end\);/);
assert.equal(Number(body.match(/c_max constant integer := (\d+);/)[1]), PROJECT_MEMORY_CHAT_MAX_CHARS);
assert.equal((body.match(/\b8000\b/g) ?? []).length, 1);
for (const [message, code] of [["Unauthorized", "42501"], ["include_in_chat is required", "P0001"], ["topic not found", "P0001"], ["topic is empty", "P0001"], ["chat inclusion limit exceeded", "P0001"]]) assert.ok(body.includes(`raise exception '${message}' using errcode = '${code}';`));
const signature = "public.set_project_memory_topic_chat_inclusion(uuid, uuid, uuid, boolean)";
assert.ok(rpc.endsWith(`revoke execute on function ${signature} from public, anon, authenticated; grant execute on function ${signature} to authenticated;`));
assert.equal((rpc.match(/grant execute/g) ?? []).length, 1);
assert.match(normalize(migration), /^begin; alter table public\.project_memory_topics add column if not exists include_in_chat boolean not null default false; drop function if exists public\.set_project_memory_topic_chat_inclusion\(uuid, uuid, uuid, boolean\); create or replace function[\s\S]*commit; notify pgrst, 'reload schema';$/);
const table = normalize(schema).match(/create table if not exists project_memory_topics \([\s\S]*?\);/)[0];
assert.match(table, /include_in_chat boolean not null default false,/);
assert.doesNotMatch(normalize(migration), /create (?:unique )?index/);
console.log("ok - v204 schema parity, signature, ACL, ordered locks, early return, budget, errors and flag-only update");
